// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:bedbug/features/content/infrastructure/models/comment_hive_model.dart';
import 'package:bedbug/features/content/infrastructure/models/content_hive_model.dart';
import 'package:bedbug/features/user/infrastructure/models/user_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CommentHiveModelAdapter());
    registerAdapter(ContentHiveModelAdapter());
    registerAdapter(UserHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CommentHiveModelAdapter());
    registerAdapter(ContentHiveModelAdapter());
    registerAdapter(UserHiveModelAdapter());
  }
}
